services:
  warp:
    image: superng6/warp-proxy:23-11-25
    container_name: warp
    mem_limit: 100m
    environment:
      # port 40000 is hardcoded
      - "PROXY_PORT=40000"
      - "WARP_LICENSE="
      - "FAMILIES_MODE=off"
    volumes:
      - ./var/lib/warp:/var/lib/cloudflare-warp
    restart: unless-stopped
  3x-ui:
    # default port 2053
    # default user admin:admin
    image: ghcr.io/mhsanaei/3x-ui:v2.4.1
    container_name: 3x-ui
    environment:
      XRAY_VMESS_AEAD_FORCED: "false"
      XUI_LOG_FOLDER: /var/log/3x-ui
    tty: true
    volumes:
      - ./var/lib/3x-ui/db/:/etc/x-ui/
      - ./var/lib/3x-ui/cert/:/root/cert/
      - ./var/log/3x-ui/:/var/log/3x-ui/
    restart: unless-stopped
