services:
  acme-sh:
    image: neilpang/acme.sh:3.0.9
    container_name: acme-sh
    volumes:
      - ./var/lib/acme-sh:/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock
    command: daemon
    stdin_open: true
    tty: true
    restart: unless-stopped
  nginx:
    image: nginx:1.27.3-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
    labels:
      - sh.acme.autoload.container=nginx
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./etc/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./var/lib/nginx/ssl:/etc/nginx/ssl
      - ./var/cache/nginx:/var/cache/nginx
      - ./var/run/nginx:/var/run
      - ./var/log/nginx:/var/log/nginx
      - ./var/www/nginx:/var/www
    networks:
      default:
        aliases:
          - mail.example.com
  #WebDAV support
#  nginx-extra:
#    image: xdrum/nginx-extras:latest@sha256:7b1d4bf13ffeedcc8c418524df45c065b81883a1b7c7ccb7122e21af64117a8a
#    container_name: nginx-extra
#    restart: on-failure
#    volumes:
#      - ./etc/nginx-extra/nginx.conf:/etc/nginx/nginx.conf:ro
#      - ./etc/nginx-extra/conf.d:/etc/nginx/conf.d:ro
#      - ./var/cache/nginx-extra:/var/cache/nginx
#      - ./var/run/nginx-extra:/var/run
#      - ./private/lib/nginx-extra:/var/www
  apache:
    image: httpd:2.4.63-bookworm
    container_name: apache
    restart: on-failure
    volumes:
      - ./etc/apache/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
      - ./etc/apache/extra:/usr/local/apache2/conf/extra:ro
      - ./var/run/apache:/usr/local/apache2/var
      - ./private/lib/apache:/usr/local/apache2/htdocs
